---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=flare_ftso_indexer
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    volumes:
      - ./config.toml:/app/config/userConfig.toml:ro
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flare_ftso_indexer
    ports:
      # You can uncomment this to connect to the database from your host machine
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
