---
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=flare_ftso_indexer
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flare_ftso_indexer
    ports:
      # You can uncomment this to connect to the database from your host machine
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
